### ISSUE TITLE
Feedback about JsonByExampleGenerator 

### ISSUE THREAD

**Issue by ignatandrei** [hermanussen/JsonByExampleGenerator#2]
Hello Robin Hermanussen

I have started a mini-e-book about Roslyn Source Code Generators(RSCG).

Your RSCG , JsonByExampleGenerator from https://github.com/hermanussen/JsonByExampleGenerator/ , is between them at https://github.com/ignatandrei/RSCG_Examples/tree/main/JsonToClass

I am thinking to add to the e-book the some more information regarding the RSCG from the authors of RSCG.

So could you please answer to the following :

1. Short info about you , Robin Hermanussen

2. Why did you start this JsonByExampleGenerator  ?

3. How do yourself use your JsonByExampleGenerator ?

4. What other RSCG do you use ? 

5. Any other feedback ?

Thanks

Andrei Ignat
http://msprogrammer.serviciipeweb.ro/

**Comment by hermanussen** [comment]
Thanks for reaching out.

**Short info about you , Robin Hermanussen**
I'm a Software Architect at Iquality (software company in the Netherlands). I'm passionate about software development in general, but with a particular interest in .NET.

**Why did you start this JsonByExampleGenerator ?**
I have written a bunch of C# analyzers in the past that served specific needs and now wanted to get some experience in writing source generators. It seemed like a good idea to me to generate classes based on example JSON, because it replaces a task that I often find a bit tedious; writing data contract classes and then tests to ensure they get properly (de)serialized with the JSON that I'm using.

**How do yourself use your JsonByExampleGenerator ?**
I'm not really using it in real world projects right now, as I'm not working on any projects that require it.

**What other RSCG do you use ?**
I've used ThisAssembly and a few others, for learning purposes.

**Any other feedback ?**
If anyone wants to use JsonByExampleGenerator and give me feedback from the real world, let me know! I'll be happy to help out with any issues or questions you may run into. Just add an issue to the project on GitHub to get in touch.

**Comment by ignatandrei** [comment]
https://github.com/ignatandrei/RSCG_Examples/tree/main/JsonToClass
