### ISSUE TITLE
Add Support For Folders In Namespace 

### ISSUE THREAD

**Issue by khalidabuhakmeh** [hermanussen/JsonByExampleGenerator#5]
If a folder is in an `API` folder, use the folder name as part of the namespace.

I think this would help avoid any name conflicts.

**Comment by hermanussen** [comment]
Interesting point, since I recently removed such functionality (https://github.com/hermanussen/JsonByExampleGenerator/issues/4).

I can understand the need for this, but I want to keep the default behavior as it currently is (for simplicity's sake). I'll think about a way to make it easily configurable. Perhaps something like this: https://github.com/hermanussen/JsonByExampleGenerator#manually-change-the-name-of-generated-types

I will keep this issue open until I figure it out.

**Comment by khalidabuhakmeh** [comment]
Very cool project by the way. I love it. Was batting the same idea around in my head, and one of my Twitter followers suggested this package.

**Comment by khalidabuhakmeh** [comment]
One more thing. This might help you as you think through this issue.

I was grabbing some `json` fragments for an HTTP JSON API and using `HttpClient` to make web requests to the API. Rather than write out the C# classes, worrying about namespaces, or other ceremonies, I was just creating `json` files in an `API` folder.

I could see creating nested folders in my project that mimicked the path names of the API for some structure and to avoid naming conflicts in case resources are repeated.

**Comment by hermanussen** [comment]
Yes, I could see that being a sensible use case. That's why, previously, I had implemented it in such a way that the namespaces would be derived from the folder in which the json was located.

However, it proved somewhat difficult to actually figure out what the namespace would then have to be; it's not impossible to include files and folders from completely different locations on the filesystem. And there would sometimes be full paths being used, which is pretty horrible.

Maybe I should take another crack at it in the future, but for now I have at least a fix coming that allows you to manually set the namespace per file.

**Comment by hermanussen** [comment]
This should do the trick: https://github.com/hermanussen/JsonByExampleGenerator#manually-change-the-namespace-for-generated-code

Thanks for reaching out and let me know if there's anything else I can help with. PRs always welcome too!
